// Generated by scripts/extract_hmrc_cds_spec.py. Do not edit by hand.
// Source files live under tmp/hmrc_tdr_audit/cds_docs.

export type CdsErrorCode = keyof typeof CDS_ERROR_CODES;

export const CDS_ERROR_CODES = {
  "CDS10001": {
    "description": "Obligation error: Mandatory Data Element has not been provided",
    "explanation": "Required details are missing - Either a DE is missing, or required information in a DE is missing/incomplete Check the declaration to ensure that all the required data elements have been completed in full. For example, if declaring a party name and address, then name, street and number, country and postcode must be completed."
  },
  "CDS10002": {
    "description": "Obligation error: Data Element is not allowed",
    "explanation": "Invalid entry on the declaration Go through the declaration from the beginning to find where you have entered details that are not permitted. Some details are not permitted at item level, only at header level - this is specified by an X or Y at the start of the value sent."
  },
  "CDS10003": {
    "description": "Obligation error: Number of Occurrences exceeds what is allowed for the Data Element",
    "explanation": "Too many instances of a data element You have exceeded the limit for one of the fields on the declaration. For example, only 1 preference code can be declared against an item."
  },
  "CDS10004": {
    "description": "Commodity code Error: Mandatory data element not provided and/or format error and/or number of occurrences exceeds what is allowed for the data element",
    "explanation": "Commodity code error A commodity code error is likely to be caused by missing or incorrect additional codes to the commodity code - these are the national additional codes or TARIC additional codes. It may also be triggered where an insufficient number of digits have been provided."
  },
  "CDS10010": {
    "description": "Format error: data element has invalid format",
    "explanation": "Invalid format One of the data elements does not comply with the minimum/maximum number of characters or uses characters not permitted. For example, the country code field with the address must only use alphabetic characters."
  },
  "CDS10020": {
    "description": "Domain error: data element contains invalid value",
    "explanation": "Invalid value A code used in the declaration is either not a recognised code or is not a code permitted on the particular declaration. For example: A document code which is only permitted on export declarations has been declared on an import declaration. A valid code has been entered on the declaration, but has been entered at the wrong level (header or item) to which it is permitted."
  },
  "CDS10021": {
    "description": "Data Error: Value must be positive",
    "explanation": "You appear to have entered a negative value A negative amount has been declared for writing off a licence. The quantity being written off for a licence must be equal to or greater than zero"
  },
  "CDS10045": {
    "description": "Calculated item Customs value is negative. Check declaration valuation data.",
    "explanation": "Valuation error The deductions you declared may exceed the value of the items. See CDS Tariff completion notes for data element 4/9. Apportioning a deduction across multiple items must not reduce the value of any single item to zero or a negative amount."
  },
  "CDS11003": {
    "description": "Relation error: The value declared in Total Number of Items (D.E. 1/9) does not correspond with the number of goods items on the declaration",
    "explanation": "You have more or fewer items than the number you declared Amend data element 1/9 to match the number of declared goods items on the declaration."
  },
  "CDS11004": {
    "description": "Relation error: The combination of Trade Movement Type, Declaration Type followed by requested procedure and /or previous procedure code is invalid.",
    "explanation": "Relation error The combination of procedure code and additional procedure code is either invalid or is not permitted on this type of declaration. Or the additional procedure code combination is not permitted."
  },
  "CDS11005": {
    "description": "Relation Error: The Requested Procedure (D.E. 1/10) for each Goods Item must derive the same Declaration Category (e.g. H1) or acceptance date is not valid. No further validation has been carried out.",
    "explanation": "Relation error All items on the declaration must derive from the same procedure category. For example if one item has requested procedure 40, then another item must not have a requested procedure of 71 because this would require a different declaration type."
  },
  "CDS11006": {
    "description": "Relation Error: Net Mass must be lower than Gross Mass",
    "explanation": "Relation error Net mass declared is greater than the gross mass declared."
  },
  "CDS11007": {
    "description": "Relation Error: The submitter of the Additional Message differs from the original declaration.",
    "explanation": "Additional message cannot be accepted A person linked to a different EORI number or different identification details cannot send a request to HMRC about the declaration, such as requesting a cancellation. Only the original declarant can send requests."
  },
  "CDS11012": {
    "description": "Element is not allowed to be amended on this declaration type",
    "explanation": "Element is not allowed to be amended on this declaration type Check your amendment request. For example, you cannot change a declaration from prelodged (D) to arrived (A) through amendment, only through goods arrival."
  },
  "CDS12003": {
    "description": "Uniqueness Error: Reuse of LRN (D.E. 2/5) is not allowed within 48 hours",
    "explanation": "Local reference number duplication You used the same local reference number (LRN) within 48 hours. Change the LRN or add a version number at the end using letters and numbers only."
  },
  "CDS12005": {
    "description": "Authorisation Error: Party ID unknown or invalid",
    "explanation": "Identification not recognised An EORI or VAT number included on the declaration is not recognised or the number used is not permitted in this DE."
  },
  "CDS12006": {
    "description": "License Error: License has expired; or License ID cannot be recognised; or License ID does not belong to the party on the declaration; or License declared has insufficient balance remaining; or License does not apply to the goods or country declared",
    "explanation": "Licence has expired, not recognised, or does not match You declared a licence number that is failing validation for one of these reasons: Expiry date is in the past Licence ID not recognised Licence DUCR not matching declaration DUCR Licence ID does not match EORI declared Licence declared has insufficient balance remaining Licence does not match country of origin specified Licence does not permit quantity declared"
  },
  "CDS12007": {
    "description": "Authorisation Error: Authorisation has expired or Authorisation reference number provided is not recognised",
    "explanation": "Authorisation number not accepted You declared an authorisation that has expired; or the reference number does not belong to the party on the declaration; or the reference number provided is not recognised."
  },
  "CDS12013": {
    "description": "Authorisation Error: provided VAT number is not a valid destination for VAT transfer",
    "explanation": "Authorisation error VAT number is not a valid destination for VAT transfer."
  },
  "CDS12014": {
    "description": "Sequence Error: A Goods Arrival Notification must follow a pre-lodged declaration.",
    "explanation": "Goods arrival notification required A goods arrival notification must follow a pre-lodged declaration."
  },
  "CDS12015": {
    "description": "Sequence Error: AdditionalMessage.declarationReference does not refer to an existing declaration or the existing declaration is not in a permissible state to process the request",
    "explanation": "Declaration status does not allow request The request to arrive, amend or cancel declaration is invalid because the declaration cannot be found or is in a state that will not allow the requested action."
  },
  "CDS12016": {
    "description": "Date Error: The acceptance date must not be in the future and must not be more than 180 days in the past.",
    "explanation": "Supplementary declaration is too late or predates acceptance The date when goods were accepted for the simplified declaration or EIDR must not be more than 365 days in the past (or 200 days for a type Q declaration) and also cannot be in the future (cannot be before the goods are accepted)."
  },
  "CDS12022": {
    "description": "Relation Error: The Good Item Number (D.E. 1/6) is larger than the total number of goods items on the declaration",
    "explanation": "Number of items error The goods item number declared is larger than the total number of goods items on the declaration."
  },
  "CDS12024": {
    "description": "Uniqueness Error: The value declared should be unique",
    "explanation": "Uniqueness error You have declared a value and repeated it, when that is not allowed. Check the entries for these data elements: 1/11 - additional procedure code can only be used once on each item 1/6 - item number cannot be repeated on the declaration 2/3 -ARC number declared with document code C651 can only be used on one declaration 4/9 - addition or deduction code can only be used once at header level or once with each item 2/3 - licence ID cannot be repeated on the same item"
  },
  "CDS12026": {
    "description": "Uniqueness Error: The same data element cannot be amended more than once in the same request.",
    "explanation": "Field has been amended more than once On amendments the same data element can only be amended once per amendment submission."
  },
  "CDS12031": {
    "description": "Sequence Error: Goods Arrival Notification must be submitted within 30 days.",
    "explanation": "Arrival notification is too late Goods arrival notification has been submitted 30 or more days after the date the declaration was originally submitted and received."
  },
  "CDS12034": {
    "description": "Relation Error: Submission channel of amendment must be the same as the original declaration.",
    "explanation": "Amendment request is invalid The amendment must be submitted using the same submission channel as the original declaration."
  },
  "CDS12036": {
    "description": "Sequence Error: A new request cannot be submitted until a response is received to your previous request.",
    "explanation": "Request not accepted There is an outstanding cancellation or amendment request. A new request cannot be submitted until a response is received to your previous request."
  },
  "CDS12042": {
    "description": "Relation error: elements must be identical within the Goods Item",
    "explanation": "Relation error Different quota order numbers cannot be declared on the same item. Note that declaration will be rejected if there is more than one quota order number in data element 8/1 for an item."
  },
  "CDS12044": {
    "description": "External Validation MUCR result: validation errors encountered",
    "explanation": "MUCR reference is invalid"
  },
  "CDS12046": {
    "description": "Process Error: Goods Arrival Notification was not received within 30 days of the pre-lodged declaration.",
    "explanation": "Goods arrival notification has not been submitted within 30 days from the date the declaration was originally received. The declaration must now be resubmitted to CDS as either arrived (where permitted) or pre-lodged and then arrived."
  },
  "CDS12050": {
    "description": "A valid Requested Procedure (D.E. 1/10) has not been provided or acceptance date is not valid. No further validation has been carried out.",
    "explanation": "Procedure code is missing or invalid Declaration must include at least one item and every item must include a valid procedure code."
  },
  "CDS12052": {
    "description": "A valid Declaration Type (D.E. 1/2) has not been provided or acceptance date is not valid. No further validation has been carried out",
    "explanation": "No valid declaration type Enter the declaration type - standard, simplified (regular use), simplified (occasional use), supplementary or clearance, and prelodged or arrived. See data element 1/2 for the correct codes."
  },
  "CDS12056": {
    "description": "Relation error: the combination of elements is not allowed",
    "explanation": "The combination of 2 values you entered is not allowed or requires another value entered For example: A document code has an incompatible document status or You have declared a code/codes which require that another code is then entered but is missing, such as an additional procedure code required for another additional procedure code to be used. or You cannot enter the customs procedure using ABDIN for Authorisation by Declaration (ABD)"
  },
  "CDS12057": {
    "description": "Relation Error: The invoice currency must be the same for every goods item on the declaration.",
    "explanation": "Invoice currency for all items must be the same See data element 4/14 for the requirement."
  },
  "CDS12058": {
    "description": "Relation Error: When the packaging quantity is zero, then there must be another goods item with the same marks and numbers having a quantity greater than zero",
    "explanation": "Number of packages error Packaging quantity cannot be zero for all packages for combined packaging"
  },
  "CDS12062": {
    "description": "External Validation DUCR result: validation errors encountered",
    "explanation": "DUCR reference is a duplication or is invalid"
  },
  "CDS12066": {
    "description": "This element or value is not allowed in combination with the declared element(s) or value(s).",
    "explanation": "Either: 1) the way the declaration has been completed requires specific DEs to also be completed with certain values. For example, required DE has not been completed or not completed correctly, or; 2) the way the declaration has been completed is not permitted. For example, the combination of DEs or their content is not allowed."
  },
  "CDS12067": {
    "description": "These elements or values are not allowed in combination with the declared element(s) or value(s).",
    "explanation": "Either a DE is not permitted to be completed on a declaration, has been completed incorrectly, or the combination of declared elements required has not been satisfied. For example: DE 8/1 Quota has been completed on a declaration where NIDOM and NIQUO are present in DE 2/2, or; DE 3/40 has been completed at header on a H8 declaration, but either APCs 'A04' or '1VW' and/or AI Statement 'PVA01' are missing."
  },
  "CDS12068": {
    "description": "This combination of elements mandates the declaration of a Document Identifier",
    "explanation": "A document code identifier is required for a specific doc code entered in DE 2/3."
  },
  "CDS12069": {
    "description": "Declaration invalidation is already being processed at the Office of Exit. Please wait for further update.",
    "explanation": "Declaration invalidation is already being processed at the Office of Exit. Please wait for further update."
  },
  "CDS12070": {
    "description": "Relation error: The value supplied in Data Element 1 mandates the completion of Data Element 2",
    "explanation": "A required field is missing a value or is invalid For example, you have entered a value that requires another field to be completed, or makes another field or code entered invalid."
  },
  "CDS12071": {
    "description": "Relation error: Data Element must be supplied at either header or item level and cannot be declared at both levels",
    "explanation": "A field has been completed at header and item level Check the data element completion guide for exports from the CDS Tariff. This tells you the exact requirements for each field. In particular see the data element completion guide for data elements 3/9, 5/8, 5/14, 7/10 and 8/5."
  },
  "CDS12072": {
    "description": "Relation error: Either Data Element 1 or Data Element 2 must be supplied, but not both",
    "explanation": "Relation error This could be an unacceptable combination of values at header and item level, for example gross weight has been declared at both header and item level. Or EORI as well as name and address has been declared for consignee, consignor or buyer."
  },
  "CDS12073": {
    "description": "Relation error: Data Element must be supplied at header or item level",
    "explanation": "Relation error A value is missing or has been entered at the wrong level. Check these data elements: 2/1, (31 or 3/2), and 8/5 must be declared at least once at either header or item level. 7/10 must be declared at least once at header or item level if 7/2 is coded 1. 3/15 or 3/16 must be declared at header level."
  },
  "CDS12074": {
    "description": "Relation error: Because Data Element 1 is not supplied, Data Element 2 is mandatory",
    "explanation": "Data elements are missing and one or the other is required Check the data element completion guide for the CDS Tariff, and declare one or the other but not both. For example, exporter, consignor and carrier, complete either an EORI or name and address. See Tariff for specific requirements"
  },
  "CDS12075": {
    "description": "Relation error: Data Element 2 must not be supplied with this value in Data Element 1",
    "explanation": "Relation error If one of the fields is completed the other should not have a value and should therefore be removed. For example, a document code and document status have been entered but the status is not required for this code. This can also indicate that a data element has been declared but is not permitted on this type of declaration."
  },
  "CDS12077": {
    "description": "Relation Error: A valid value must be supplied in Data Element 2 as Data Element 1 is present",
    "explanation": "Relation error affecting one or more additional completion requirements For example, the completion of one DE with a certain value/code requires another value/code to be entered in the same DE or a different DE (such as not entering 00100 in DE 2/2 when ABDIN is entered in DE 2/2 etc), or; the DE itself has not been fully completed/populated as required (such as an address not fully completed when a name is provided in DE 7/14 etc). or; the DE has been completed incorrectly, for example DE 4/4 measurement units KTC or CTG cannot have zero values."
  },
  "CDS12078": {
    "description": "Relation Error: As no Deferment Account Number is provided in D.E. 2/6, an immediate Method of Payment must be offered in D.E. 4/8",
    "explanation": "Relation Error: As no Deferment Account Number is provided in D.E. 2/6, an immediate Method of Payment must be offered in D.E. 4/8"
  },
  "CDS12079": {
    "description": "Relation Error: Data Element 2 must not be supplied with Data Element 1",
    "explanation": "Relation error - Two values you declared are incompatible. For example: A data element is declared at both header and item levels but only one level is permissible; You have entered a MUCR in DE 2/1 for a GVMS location code in DE 5/23."
  },
  "CDS12080": {
    "description": "Relation error: Combination of Addition / Deduction codes (DE 4/9) is not allowed",
    "explanation": "Relation error You have used a mix of addition or deduction codes for an item that is not permitted. Certain addition/deduction codes cannot be declared together. Additions and deductions should only be declared at header level where they apply to all good items on the customs declaration. Each addition or deduction code can only be declared once at header level. The same addition or deduction code cannot then be declared at item level as well. If a specific addition or deduction is being declared at item level, that addition or deduction may only be declared once per item."
  },
  "CDS12081": {
    "description": "Relation Error: Importer (D.E. 3/16) & Exporter (D.E. 3/2) must not be the same party",
    "explanation": "Relation Error: Importer (D.E. 3/16) & Exporter (D.E. 3/2) must not be the same party"
  },
  "CDS12082": {
    "description": "Relation error: The currency declared in DE 4/11 must be the same as the currency declared in DE 4/14",
    "explanation": "Relation error The currency declared for the total amount invoiced does not match the currency declared at item price amount (data element 4/14)."
  },
  "CDS12083": {
    "description": "Relation Error: For Country of Preferential Origin DE 5/16 where mandated, only provide one country or country group, not both",
    "explanation": "Relation error You have provided both a country and country group for mandatory data element Preferential Origin. Where the proof of origin document refers to a group of countries, enter the group of countries by using the relevant Union codes in accordance with the codes listed in Appendix 13: Country Codes. Where data element 5/16 is completed using a preference group code, data element 5/15 must be completed with the specific country of origin for the goods."
  },
  "CDS12084": {
    "description": "Relation error: Either Consignee Name (DE 3/9) or Consignee Identification Number (DE 3/10) must be supplied, but not both",
    "explanation": "Consignee details You have provided both consignee name and consignee EORI. Only declare either the EORI or the full name and address of consignee not both. EORI should be declared when known."
  },
  "CDS12086": {
    "description": "Relation error: Either Carrier Name (DE 3/31) or Carrier Identification Number (DE 3/32) must be supplied, but not both",
    "explanation": "Carrier details You have provided both Carrier name and Carrier EORI. Only declare either the EORI or the full name and address of carrier not both. EORI should be declared when known."
  },
  "CDS12087": {
    "description": "Relation error: VAT Declaring Party Identification (DE 3/40), where mandated, must be supplied at either header or item",
    "explanation": "Additional fiscal party You have declared your additional fiscal party VAT number at both header and item level. It should only be declared at either item or header level. Or you have declared procedure code 1042 and not declared an additional fiscal references ID."
  },
  "CDS12088": {
    "description": "Relation error: Either Agent Name (DE 3/19) or Agent Identification Number (DE 3/20) must be supplied",
    "explanation": "Representative details missing To correct this error, complete the EORI in data element 3/19, or the name and address in 3/20, even if they are your own details as the declarant and you are the direct representative."
  },
  "CDS12089": {
    "description": "Relation error: Consignee Party Name (DE3/9) must be supplied at either header or item level",
    "explanation": "Consignee party details Consignee party name and address must be declared at either header or item level on a C21e unless the procedure code is 0019."
  },
  "CDS12090": {
    "description": "Relation error: Carrier Name (DE 3/31) or Carrier Identification Number (DE 3/32) must be supplied for the 17X Additional Procedure Code at either header or item level",
    "explanation": "Carrier EORI When declaring additional procedure Code 17X on a C21e clearance request, the carrier name and address or the carrier EORI must be declared at header level."
  },
  "CDS12091": {
    "description": "Relation error: Consignee (D.E. 3/10) & Exporter (D.E. 3/1) must not be the same Party",
    "explanation": "Relation error Consignee (receiver of goods) and exporter cannot have the same EORI number."
  },
  "CDS12092": {
    "description": "Relation error: Seller (DE 3/25) & Exporter (DE 3/1) must not be the same Party",
    "explanation": "Relation error You have declared the same party for seller (data element 3/25) and exporter (data element 3/1). The seller details are only required where the seller is a different party to the exporter. Where the seller is a different party to the exporter and holds a recognised EORI number, enter the seller’s EORI number in data element 3/25."
  },
  "CDS12095": {
    "description": "Relation error: Additional Procedure Combination (DE 1/11) can only be used when Country of Dispatch/Export (DE 5/14) Exportation Country is a Third Country",
    "explanation": "Relation error You have used an additional procedure combination (data element 1/11) incorrectly. Additional procedure codes 1IL and 1LV can only be used for goods dispatched/exported from a third country."
  },
  "CDS12096": {
    "description": "Relation error: Provided Authorisation Type (D.E. 3/39) requires specific document in Additional Documents",
    "explanation": "Authorisation error When declaring any of the authorisation types CGU, EUS, IPO or TEA in data element 3/39, it is necessary to declare document code C505 (Customs Comprehensive Guarantee) in DE 2/3. It may be necessary to declare C505 together with a waiver status code such as XW."
  },
  "CDS12097": {
    "description": "Relation error: Combination Additional Procedure Code (D.E. 1/11) and Country of Destination in DE 5/8 is not allowed",
    "explanation": "Relation error When declaring Additional Procedure Code F75, the destination country must be a Special Fiscal Territory or other territory with which the EU has formed a Customs Union."
  },
  "CDS12098": {
    "description": "Relation Error: Combination of Means of Transport (DE 7/4) and Delivery Terms in DE 4/1 is not allowed",
    "explanation": "Relation error You have declared a means of transport code (data element 7/4) that is not compatible with the delivery terms (data element 4/1)."
  },
  "CDS12099": {
    "description": "Relation error: Combination of elements that make up the Goods Location code (5/23) is invalid",
    "explanation": "Goods location code not recognised Check the codes listed in Appendix 16 and in the supplements to Tariff, where new goods location codes may be listed."
  },
  "CDS12100": {
    "description": "Relation Error: Combination of Delivery terms (DE 4/1) and Addition/Deduction code (DE 4/9) is not allowed",
    "explanation": "Relation error You have declared Delivery Terms (data element 4/1) that are not compatible with the Addition/Deduction code (data element 4/9). The combination of Delivery Terms and Addition/Deduction Code must be compatible."
  },
  "CDS12101": {
    "description": "Relation error: Declared Tax Type (DE4/3) is not allowed in combination with the Additional Procedure",
    "explanation": "Relation error You have declared an additional procedure code that is not permitted to be combined with the declared tax type (data element 4/3). For example, additional procedure codes 32D, 31D, 1IL and 1LV cannot be used with an excise tax type."
  },
  "CDS12102": {
    "description": "Relation error: Deferred Payment Method in DE 4/8 is Required with the duty deferment account number provided in DE 2/6",
    "explanation": "Relation error You have not declared the deferred payment method which is required for the duty deferment account number declared."
  },
  "CDS12103": {
    "description": "Relation error: Valid delivery destination is required in D.E.5/8 for a CO declaration",
    "explanation": "Relation error When declaring Declaration Type code CO in data element 1/1, the destination country must be a Special Fiscal Territory or other territory with which the EU has formed a Customs Union."
  },
  "CDS12104": {
    "description": "Relation error: Valid Import Procedure code (1/10) is required",
    "explanation": "Relation error For declaration type code IM, the procedure code must be a permitted import procedure code. Check Appendix 1 of the Import Tariff and the Inventory Import Tariff"
  },
  "CDS12105": {
    "description": "Relation error: Addition/Deduction code (DE 4/9) not allowed with the declared Additional Procedure Code (DE1/11)",
    "explanation": "Relation error When using additional procedure code E01 (simplified procedure value) or E02 (standard import value), data element 4/9 additions and deductions, must not be declared. See Appendix 1 for more information."
  },
  "CDS12106": {
    "description": "Relation error: Appropriate Additional Information Code must be provided in DE2/2 with Additional Procedure Code 1CL",
    "explanation": "Relation error An appropriate Additional Information (AI) code is required with the additional procedure code 1CL."
  },
  "CDS12107": {
    "description": "Relation error: Conditions not met for the requested simplification. Please see CDS Trade Tariff Vol.3 Appendix 4",
    "explanation": "Relation error When using Additional Information code 00600, data element 2/3 must not include any licence document codes, even if claiming a waiver/exemption."
  },
  "CDS12108": {
    "description": "Obligation Error: DUCR is mandatory on an Export Declaration",
    "explanation": "Obligation error Declaration Unique Consignment Reference (DUCR) is mandatory at header level on an export declaration."
  },
  "CDS12109": {
    "description": "Obligation Error: When providing fixed rate of exchange rate in DE 4/15, a currency code of GBP must be supplied",
    "explanation": "Total invoiced amount should be in GBP You declared a fixed rate of exchange meaning a contractually agreed rate of exchange was used. The invoice value (data element 4/14) on an import declaration or the total amount invoiced (data element 4/11) on an export declaration, needs to be declared in GBP, converted using the agreed rate."
  },
  "CDS12110": {
    "description": "Relation error: A Quota Order number (DE8/1) cannot be provided in combination with this Preference Code (DE 4/17)",
    "explanation": "Relation error The Preference Code declared (data element 4/17) is incompatible with claiming Quota (data element 8/1)."
  },
  "CDS12111": {
    "description": "Relation error: The provided tax amount (DE 4/6 or DE 4/7) must always be declared with currency code GBP",
    "explanation": "Relation error You have declared the tax amount (data element 4/6 or 4/7) in the incorrect currency. Tax amounts should always be declared with the sterling GBP currency code."
  },
  "CDS12112": {
    "description": "Relation error: Airfreight related additions/deduction code must be provided in DE 4/9 when an airport place of loading is provided in DE 5/21",
    "explanation": "Addition/deduction code missing You have not provided the mandatory airfreight related addition/deduction code (data element 4/9) for the declared airport place of loading (data element 5/21)."
  },
  "CDS12113": {
    "description": "Relation error: Authorisation holder CGU requires a guarantee type of 0 or 1 to be provided in D.E.8/2",
    "explanation": "Authorisation CGU requires a guarantee Holder of authorisation type CGU has been declared and so guarantee type in data element 8/2 must be 0 (Guarantee Waiver) or 1 (Comprehensive Guarantee)."
  },
  "CDS12114": {
    "description": "Relation error: Value declared must be less than 100 as DE 4/9 Additions/Deductions code is a percentage",
    "explanation": "Relation error The value you declared may not be less than 100%. The Additions/Deductions code is a percentage and so the value provided in data element 4/9 must be less than 100."
  },
  "CDS12115": {
    "description": "Relation error: Declared Procedure Code (DE 1/10 and / or 1/11) mandates the use of Additional Document (DE 2/3) 185C",
    "explanation": "Relation error You have not have declared document code 185C (Claim to Visiting Forces Relief for goods removed from a customs warehouse), required for the additional procedure code entered."
  },
  "CDS12117": {
    "description": "Relation error: Importer (DE 3/16) & Buyer (DE 3/27) must not be the same party",
    "explanation": "Relation error You have declared the same EORI for the Importer and Buyer on an import declaration."
  },
  "CDS12118": {
    "description": "Relation error: Consignor (DE3/1) information must be supplied for the 17X Additional Procedure Code at either header or item level and cannot be declared at both levels",
    "explanation": "Relation error You have declared consignor details for the additional procedure code 17X at both header and item level. It should only be declared at either item or header level."
  },
  "CDS12119": {
    "description": "Relation error: Declared Additional Document (D.E. 2/3) is not allowed with this Procedure Code (D.E. 1/10 or D.E. 1/11)",
    "explanation": "Additional document not allowed or is missing Additional document code, for example licence, exemption or authorisation number, is not allowed or must not be declared with other data in the declaration. Examples include C512 and C514 (SDP and EIDR authorisations) not permitted with certain procedure codes; licence document code restrictions with certain additional procedure codes, Special Procedure authorisations required with certain procedure combinations."
  },
  "CDS12120": {
    "description": "Relation Error: The appropriate authorisation has not been declared for this Declaration Type (D.E. 1/2)",
    "explanation": "Authorisation error You may not have declared an authorisation required for this declaration type. If you have declared the correct authorisation, check the authorisation number declared on the 'Additional documentation' page. For SDP declarations, you need document code C512 For EIDR declarations, you need document code C514 For submitting an arrived export declaration, data element 3/39 must include one of the authorisation type codes CSE or EXRR. You may have declared an authorisation that has expired; or the reference number does not belong to the party on the declaration; or the reference number provided is not recognised."
  },
  "CDS12121": {
    "description": "Relation Error: This combination of Additional Information codes (D.E. 2/2) is not allowed",
    "explanation": "There is an error with the Additional Information codes against a goods item. Either, the AI codes declared together for one goods item are not compatible with each other, or an AI code entered for the goods item mandates another AI is present."
  },
  "CDS12123": {
    "description": "Data Error: Value must be greater than 0",
    "explanation": "A value declared must be equal to or greater than 0. For example: -Invoice value declared in DE 4/14 must be greater than 0. -Package quantity in DE 6/10 must be greater than or equal to 0."
  },
  "CDS12125": {
    "description": "DAN Error: Account number is not recognised; or Account is suspended or revoked; or Parties declared on the declaration do not have authority to use account number provided",
    "explanation": "DAN error The deferment account number or Guarantee reference Number you have provided - is not recognised or - the account may be suspended/revoked or - Parties declared on the declaration do not have authority to use account number provided. Check the CDS financial dashboard/contact HMRC deferment department."
  },
  "CDS12132": {
    "description": "DUCR format not valid",
    "explanation": "Declaration Unique Consignment Reference (DUCR) format is not valid"
  },
  "CDS12133": {
    "description": "MUCR format not valid",
    "explanation": "MUCR format is not valid If the MUCR was given to you, check it is in a valid format. If you created it yourself, check the guidance on the correct format (opens in new tab)."
  },
  "CDS12134": {
    "description": "DUCR and MUCR formats not valid",
    "explanation": "MUCR or DUCR format is not valid If the MUCR was given to you, check it is in a valid format. If you created it yourself, check the guidance on the correct format (opens in new tab). If you have declared a previous declaration reference such as for an import, check the DUCR on the previous declaration."
  },
  "CDS12135": {
    "description": "Relation Error: Country of Export (DE 5/14) must be supplied at either header or item level",
    "explanation": "Relation error Country of export is mandatory at header or item level when declaring additional procedure code 1CD, 1CG, 2CG or 2CD. On a C21I with procedure code 0002, 0003, 0004, 0005, 0006 or 0007."
  },
  "CDS12136": {
    "description": "Relation Error: Provided Additional Procedure Code (DE 1/11) necessitates indirect representation (DE 3/21) for the following declaration types: C F Y J K Z",
    "explanation": "Relation error The additional procedure code declared requires this declaration to have indirect representation (data element 3/21). The representative status declared in data element 3/21 would show Indirect, code ‘3’. The representative status declared in data element 3/21 indicates the relationship between the representative and the importer, not the sub-agent and any other party."
  },
  "CDS12137": {
    "description": "Uniqueness Error: Only a single MUCR can be declared in DE 2/1 at Header level on an imports declaration",
    "explanation": "Uniqueness error You have declared more than one MUCR at header level on your import declaration."
  },
  "CDS12138": {
    "description": "Relation Error: Provided Additional Procedure Code (D.E. 1/11) cannot be used on a Type J/K (EIDR) declaration",
    "explanation": "Additional procedure code is not allowed These additional procedure codes cannot be used with an EIDR C21 declaration. 1CD - Controlled drugs using Simplified Procedures 1CG - Controlled Goods using Simplified Procedures"
  },
  "CDS12139": {
    "description": "Relation Error: Additional Information Code OVR01 must be provided in DE 2/2 when entering a manual tax amount in DE 4/6 or DE 4/7",
    "explanation": "Relation error You have not provided the Additional Information (AI) Code OVR01 required for the declared manual tax amount in data element 4/6 or 4/7."
  },
  "CDS12141": {
    "description": "Relation Error: Incompatible goods movements declared. AI codes 'NIDOM' and 'NIIMP' must not be entered together on the same declaration.",
    "explanation": "Relation error You have declared a combination of Additional Information Codes 'NIDOM' and 'NIIMP' that are not permitted to be declared together on the same declaration."
  },
  "CDS12143": {
    "description": "Incompatible goods movements declared. AI codes 'NIREM' and 'NIAID' must not be entered together on the same goods item on a declaration.",
    "explanation": "DE 2/2 AI statement error The combination of NI Additional Information Codes are not permitted to be declared together on the same goods item"
  },
  "CDS12144": {
    "description": "Relation Error: EU Quota order number beginning '09' must not be entered in DE 8/1 for any imports into the UK",
    "explanation": "Relation error You have entered the incorrect EU Quota order number beginning with '09' which is not permitted for imports into the UK."
  },
  "CDS12145": {
    "description": "Relation Error: When declaring the Requested Procedure code 42 in DE 1/10, the Additional Information code NIIMP must be declared in DE 2/3",
    "explanation": "Relation error For the Requested Procedure code 42 in data element 1/10 the Additional Information code, NIIMP, must be declared in data element 2/2."
  },
  "CDS12146": {
    "description": "The Requested Procedure code 42 (DE 1/10) and Additional Information code OSR42 (DE 2/2) must be entered together on the same goods item",
    "explanation": "Relation error You have not entered either the Requested Procedure code 42 (DE 1/10) or Additional Information code OSR42 (DE 2/2) on the same goods item."
  },
  "CDS12147": {
    "description": "Relation Error: UVC01 declared on an original declaration. UVC01 can only be declared on an amendment request for a declaration",
    "explanation": "Additional Information (AI) code is not allowed AI code UVC01 may only be used on an amendment."
  },
  "CDS12148": {
    "description": "Relation Error: Additional Document C506 requires deferred payment method",
    "explanation": "Relation error You have not provided a deferred payment method for the declared Additional Document C506."
  },
  "CDS12149": {
    "description": "Relation Error: Additional Procedure code 000 can not be declared with any other Additional Procedure Code",
    "explanation": "Relation error Additional procedure code 000 can not be declared with any other additional procedure code"
  },
  "CDS12150": {
    "description": "Authorisation Error: Authorisation reference number does not belong to the party on the declaration",
    "explanation": "An authorisation number is invalid An authorisation number, such as for a Special Procedure, SDP, EIDR, CCG, Customs Warehousing, national authorisation, is either not valid or is not authorised for use by the party given on the declaration."
  },
  "CDS12151": {
    "description": "Relation Error: When a licence is declared, ID must be unique from all other additional documents (DE 2/3) in the same goods item",
    "explanation": "Duplication error For example: Licence ID cannot be declared more than once on the same item in DE 2/3."
  },
  "CDS12152": {
    "description": "Additional Procedure Code (DE 1/11) 1H7 can only be used when submitting an SRDS declaration and is required to be declared on all goods items.",
    "explanation": "An additional procedure code is missing for an H7/SRDS declaration: Additional Procedure Code '1H7' must be present for the H7/SRDS declaration category."
  },
  "CDS12153": {
    "description": "Relation Error: EORIs with this country code are not supported",
    "explanation": "Relation Error The country code at the start of an EORI must be GB when declaring any of the parties Importer (DE 3/16), Exporter (DE 3/2), Declarant (DE 3/18), Representative (DE 3/20)."
  },
  "CDS12154": {
    "description": "Incompatible goods movements declared. When AI code 'NIIMP', 'NIDOM' or 'NIEXP' is entered at item level in D.E. 2/2, Document Code – 999L cannot be entered in D.E.2/3",
    "explanation": "The Document Code 999L cannot be used for goods being imported or exported from Northern Ireland. Please use the UK/NI online tariff to identify the document codes, other than 999L, required by the measure conditions on your commodity code."
  },
  "CDS12155": {
    "description": "Uniqueness Error: Only one instance of 999L may be declared in D.E. 2/3 per goods item",
    "explanation": "Uniqueness Error The document code 999L can only be declared once per goods item. It does not have to be declared for each measure for which a waiver applies on that goods item. For example, if a goods item has two measures for which 999L is available to declare a waiver, declaring it once for that goods item will suffice to satisfy both measures. Declaring it twice will result in this rejection."
  },
  "CDS12156": {
    "description": "Obligation Error: Mandatory Data Element has not been provided or the ID for previous document CLE must match the AcceptanceDate in the format yyyymmdd",
    "explanation": "The declaration Acceptance Date is missing or not in the correct format against Previous Document Code 'CLE'"
  },
  "CDS12157": {
    "description": "Invalid EORI - This Party must have a permanent business establishment in Northern Ireland or the European Union",
    "explanation": "A relevant party on the declaration does not have the status of 'established in the Union', for the purposes of an NI declaration."
  },
  "CDS12158": {
    "description": "Missing Element - A non-GB EORI requires entry of NI Movement AI Codes in DE 2/2",
    "explanation": "A relevant party on an NI declaration has been entered with an XI EORI number, however no NI AI statements (NIIMP, NIDOM, NIEXP) are present."
  },
  "CDS12170": {
    "description": "Authorisation Error: Invalid VAT number. Please note, if you are attempting to claim Onward Supply Relief (OSR), you must be identified as trading under the terms of the Northern Ireland Protocol (now Windsor Framework) for VAT.",
    "explanation": "Authorisation Error: Invalid VAT number. Please note, if you are attempting to claim Onward Supply Relief (OSR), you must be identified as trading under the terms of the Northern Ireland Protocol (now Windsor Framework) for VAT."
  },
  "CDS12171": {
    "description": "Relation Error: The values supplied in Data Element 1 and Data Element 2 require a valid value to be provided in Data Element 3.",
    "explanation": "Due to the way the declaration has been completed, a further DE must be completed or completed in a certain way - For example, on an NI export dec if DE 7/4 is either 1, 3, 4, 8 or 9 then DE 7/15 must be completed."
  },
  "CDS12172": {
    "description": "Relation Error: The values supplied in Data Element 1 and Data Element 2 require a valid value to be provided in Data Element 3 and/or Data Element 4.",
    "explanation": "Due to the way the declaration has been completed, a further DE must be completed or completed in a certain way - For example, on an NI export supp dec if DE 7/2 is '1' for containerised, a containder ID must be provided in DE 7/10 at header or item."
  },
  "CDS12174": {
    "description": "Relation Error: The value declared in Total amount invoiced (D.E. 4/11) does not correspond with the total of all item price amounts (D.E. 4/14) on the declaration",
    "explanation": "Relation Error: The value declared in Total amount invoiced (D.E. 4/11) does not correspond with the total of all item price amounts (D.E. 4/14) on the declaration"
  },
  "CDS12500": {
    "description": "Validation error: value limit exceeded",
    "explanation": "The value entered into a specific DE exceeds the amount permitted - Please consult the Tariff Volume 3 for the limits permitted for the procedure/relief in question."
  },
  "CDS13000": {
    "description": "Credibility check: incredible value found",
    "explanation": "Value fails credibility check as too high or too low"
  },
  "CDS14000": {
    "description": "Credibility check: incredible quota value found",
    "explanation": "Value fails credibility check as too high or too low"
  },
  "CDS19999": {
    "description": "Additional errors found",
    "explanation": "Declaration has multiple errors Contact the help desk."
  },
  "CDS20001": {
    "description": "Related movement not (yet) found",
    "explanation": "Related movement not found"
  },
  "CDS20002": {
    "description": "Related movement does not match declaration",
    "explanation": "Related movement does not match declaration"
  },
  "CDS20003": {
    "description": "Related movement not found",
    "explanation": "Related movement not found"
  },
  "CDS40007": {
    "description": "Duplicate value",
    "explanation": "Duplication error For example, the same Additional TARIC or National additional code has been declared twice for one item."
  },
  "CDS40010": {
    "description": "Data element value does not apply",
    "explanation": "Value given for a data element does not apply This could be a formatting error or a code incorrectly completed."
  },
  "CDS40011": {
    "description": "Missing data element value",
    "explanation": "Missing data element value A value that is required by the commodity code has not been completed. For example, supplementary unit. You need to check the 'Measures' column for the commodity code on the Trade Tariff."
  },
  "CDS40012": {
    "description": "At least one of the commodity codes you have declared requires additional information that cannot be provided on this dataset. Please use the standard full export declaration dataset (B1) instead.",
    "explanation": "At least one of the commodity codes you have declared requires additional information that cannot be provided on this dataset. Please use the standard full export declaration dataset (B1) instead."
  },
  "CDS40013": {
    "description": "Data element contains invalid value",
    "explanation": "A DE contains invalid information related to a Tariff measure/condition - For example, the Preference code in DE 4/17 is incorrect. Where this is in relation to a measurement unit error on DE 6/2 and/or DE 4/4: This can be due to the values supplied being invalid, or an incorrect combination has been entered. For example, supplying both LPA and ASV in DE 4/4 against an excise tax type that does not permit this combination. It can also indicate that two instances of the same measurement amount do not align. For example, the DE 6/2 Supplementary unit amount in litres differs to the amount entered against a measurement unit LTR in DE 4/4."
  },
  "CDS40044": {
    "description": "Disallowed Document",
    "explanation": "Document declared is not allowed for the given commodity code You need to check the 'Conditions' box for the commodity code on the Trade Tariff. If you do not hold any licence, you must decide if you can declare a waiver (usually a Y-code). Instructions for how to use the code are given in the 'Conditions' box for the commodity code and Appendix 5A."
  },
  "CDS40045": {
    "description": "Missing document",
    "explanation": "A document is missing The licence or exemption required for these goods is missing. You need to check the 'Conditions' box for the commodity code on the Trade Tariff. If you do not hold any licence, you must decide if you can declare a waiver (usually a Y-code). Instructions for how to use the code are given in the 'Conditions' box for the commodity code and Appendix 5A."
  },
  "CDS40047": {
    "description": "Prohibition",
    "explanation": "Value not allowed"
  },
  "CDS40049": {
    "description": "Quota exhausted",
    "explanation": "Quota used up"
  },
  "CDS40053": {
    "description": "Quota suspended",
    "explanation": "Quota suspended"
  },
  "CDS40059": {
    "description": "Incomplete measure or commodity code",
    "explanation": "Incomplete measure or commodity code"
  },
  "CDS40066": {
    "description": "Tariff condition not fulfilled",
    "explanation": "Tariff condition not fulfilled Value is not allowed to be used for the given commodity code. You need to check the 'Measures' box for the commodity code on the Trade Tariff. If you do not hold any licence, you must decide if you can declare a waiver (usually a Y-code). Instructions for how to use the code are given in the 'Conditions' box for the commodity code and Appendix 5A."
  },
  "CDS40068": {
    "description": "Additional Excise code is missing",
    "explanation": "National additional code for excise is missing"
  },
  "CDS40069": {
    "description": "Quota Closed",
    "explanation": "Quota error The Quota claimed is no longer available."
  },
  "CDS40070": {
    "description": "When AI code 'NIIMP' is entered at item level in D.E. 2/2, it must be declared on all goods items in the declaration.",
    "explanation": "Additional information code NIIMP must appear on all items Additional information code NIIMP when used on one item must be entered on all items."
  },
  "CDS40071": {
    "description": "When AI code 'NIDOM' is entered at item level in D.E. 2/2, it must be declared on all goods items in the declaration",
    "explanation": "Additional information code NIDOM must appear on all items Additional information code NIDOM when used on one item must be entered on all items."
  },
  "CDS40072": {
    "description": "When AI code 'NIEXP' is entered at item level in D.E. 2/2, it must be declared on all goods items in the declaration",
    "explanation": "Additional information code NIEXP must appear on all items Additional information code NIEXP when used on one item must be entered on all items."
  },
  "CDS40073": {
    "description": "When de-risking AI code 'NIREM' is entered at item level in D.E. 2/2, either 'NIIMP' or 'NIDOM' AI codes must also be entered at item level on the same goods item",
    "explanation": "You declared NIREM additional information code on its own NIREM additional information (AI) code may not be declared in isolation; NIDOM or NIIMP must also be declared on the same item."
  },
  "CDS40074": {
    "description": "When subsidy AI code 'NIAID' is entered at item level in DE 2/2, either 'NIIMP' or 'NIDOM' AI codes must also be entered at item level on the same goods item",
    "explanation": "Relation error You have not entered either 'NIIMP' or 'NIDOM' AI codes when you declared subsidy AI code 'NIAID'. Either of these codes are required to be entered at item level on the same good item."
  },
  "CDS49999": {
    "description": "Other errors",
    "explanation": "Other Errors"
  },
  "CDS50000": {
    "description": "Response from ALVS is not release",
    "explanation": "Response from ALVS is not release"
  },
  "CDS50001": {
    "description": "Invalid UCR Format, DUCR or MUCR",
    "explanation": "Invalid UCR Format, DUCR or MUCR"
  },
  "CDS50003": {
    "description": "UCR is not at the top of its' consolidation",
    "explanation": "UCR is not at the top of its consolidation"
  },
  "CDS50008": {
    "description": "UCR Type does not match UCR Format",
    "explanation": "DUCR or MUCR is not the right format"
  },
  "CDS50015": {
    "description": "Declaration is cancelled/terminated/invalidated/handled externally/rejected (upon arrival)",
    "explanation": "Declaration is cancelled or terminated upon arrival Declaration is cancelled/terminated/invalidated/handled externally/rejected (upon arrival)."
  },
  "CDS50018": {
    "description": "Goods Arrival Date/Time is invalid or not included",
    "explanation": "This is an ILE error code and is returned for Inventory linking."
  },
  "CDS50027": {
    "description": "Role/Location-Based Authorisation failed (PDS)",
    "explanation": "Authorisation failed"
  },
  "CDS50028": {
    "description": "Goods Location is invalid",
    "explanation": "Goods location code invalid The codes declared in the goods location code field must be selected from the code lists shown in Appendix 16."
  },
  "CDS50031": {
    "description": "Request has been received after a successful RET",
    "explanation": "Request has been received after a successful RET"
  },
  "CDS70711": {
    "description": "Licence Error: Electronic licence does not exist",
    "explanation": "Licence error Electronic licence does not exist."
  },
  "CDS70719": {
    "description": "Licence Error: Electronic licence quoted although Document Status Code indicated paper licence",
    "explanation": "Licence error Electronic licence quoted but document status code indicates paper licence. Check the document status code."
  },
  "CDS70724": {
    "description": "Licence Error: Licence is not valid",
    "explanation": "Licence reference quoted is not valid This could be because: licence does not match the commodity code licensing authority declared is incorrect licence is out of date licence allows insufficient quantity licence reference number declared is incorrect licence does not belong to the importer/ exporter declared licence is not valid for the country of origin/ dispatch/ destination licence does not match the DUCR declared in DE 2/1 If still stuck, contact the licencing authority"
  },
  "CDS70739": {
    "description": "Licence Error: An Import licence cannot be used on an Export declaration",
    "explanation": "Licence error Import licence cannot be used on an export declaration."
  },
  "CDS70740": {
    "description": "Licence Error: Importer/Exporter is not the owner of the licence",
    "explanation": "Licence error Importer/Exporter is not the owner of the licence and/or licence is not valid."
  },
  "CDS70758": {
    "description": "Licence is not valid for declared Country of Destination",
    "explanation": "Licence error Licence is not valid for declared country of destination."
  },
  "CDS70760": {
    "description": "Licence Error: Licence is not valid for the declared goods item",
    "explanation": "Licence is not valid for this item This could be because: licence does not match the commodity code licensing authority declared is incorrect licence is out of date licence allows insufficient quantity licence reference number declared is incorrect licence does not belong to the importer/ exporter declared licence is not valid for the country of origin/ dispatch/ destination licence does not match the DUCR declared in DE 2/1 If still stuck, contact the issuing authority"
  },
  "CDS70761": {
    "description": "Licence has insufficient quantity remaining to meet claim",
    "explanation": "Licence error Licence does not cover the quantity declared."
  },
  "CDS70791": {
    "description": "Licence Error: Licence line number does not exist on the licence",
    "explanation": "Licence error Line number given on licence is not valid."
  },
  "CDS71115": {
    "description": "Licence Error: An Export licence cannot be used on an Import declaration",
    "explanation": "Licence error Export licence cannot be used on an import declaration."
  },
  "CDS71200": {
    "description": "Uniqueness Error: Document Codes with identical IDs are not permitted on a single goods item",
    "explanation": "Document reference is a duplication You cannot use the same reference on a single goods item."
  },
  "CDS71201": {
    "description": "Licence Error: All instances of a licence for a declaration must use a consistent Document Status Code",
    "explanation": "Licence error All instances of a licence for a declaration must use a consistent Document Status Code."
  },
  "CDS71203": {
    "description": "Licence Error: Document Status Code \"EL\" or \"EP\" is not allowed on a Single Use licence",
    "explanation": "Licence error Document status code \"EL\" or \"EP\" is not allowed on a single use licence. The licence can only be used once so cannot be part used."
  },
  "CDS71204": {
    "description": "Licence is already surrendered",
    "explanation": "Licence is already surrendered"
  },
  "CDS71206": {
    "description": "Licence is already exhausted",
    "explanation": "Licence is already exhausted"
  },
  "CDS71216": {
    "description": "Transaction not permitted; Licence is inactive and is no longer available for use",
    "explanation": "Licence is no longer available for use Licence declared has been made inactive, check correct licence is declared or contact issuing authority."
  },
  "CDS71236": {
    "description": "Licence not valid for declared Country of Origin",
    "explanation": "Licence error You have declared an invalid Licence for the declared Country of Origin."
  },
  "CDS71252": {
    "description": "Licence not valid for declared Country of Dispatch",
    "explanation": "Licence error Licence not valid for declared country of dispatch"
  },
  "CDS71262": {
    "description": "Licence Error: Document Status Code \"EA\" can only be declared on Type Y declaration",
    "explanation": "Licence error Document Status Code \"EA\" can only be used on a supplementary declaration."
  },
  "CDS73329": {
    "description": "Licence Error: Licence cannot be declared on declaration category/declaration type combination",
    "explanation": "Licence cannot be used A licence document code (for example X002, 9106) cannot be declared on this type of declaration, even if using a waiver/exemption document status code. If the goods are entitled to a waiver/exemption and there is a waiver document code which can be used in place of the licence document code (for example Y903, Y927), then this can be used instead. If there is no waiver document code that can be used then it may be necessary to use a standard declaration."
  },
  "CDS77000": {
    "description": "Obligation Error: ID must be provided for declared Document Code",
    "explanation": "Document identifier required Instructions for how to use the code are given in the 'Conditions' box for the commodity code and Appendix 5A."
  },
  "CDS77001": {
    "description": "Quantity must be provided for Document Category",
    "explanation": "Quantity must be provided In some cases, when you declare a document status code to indicate a waiver for a licence, you are still required to enter a '0' as the quantity attributed to the licence. This will also require a measurement unit such as GBP."
  },
  "CDS77002": {
    "description": "Obligation Error: Document Status Code must be provided for declared Document Code",
    "explanation": "Document status code needed Check appendix 5A for more information."
  },
  "CDS77003": {
    "description": "Licence Error: DUCR must be provided for an Import declaration with a Licence",
    "explanation": "Licence error You have not provided a DUCR - this is required at header level for an import declaration with a licence."
  },
  "CDS77004": {
    "description": "Reservation could not be made",
    "explanation": "Reservation could not be made"
  },
  "CDS77005": {
    "description": "Reason for waiver must be declared for Document Category",
    "explanation": "Reason not given for use of a 'Y' code The Y series document code used requires a document reason. Check the 'Conditions' box in the Online Tariff or appendix 5A for the information required."
  }
} as const;

