name = "cloudagent"
main = "src/index.ts"
account_id = "555e307a91082ae8c8e69b0a5ff3b8c3"
compatibility_date = "2024-10-22"
compatibility_flags = [ "nodejs_compat" ]

[[vectorize]]
binding = "HMRC_ERRORS_VECTORIZE"
index_name = "hmrc-cds-errors"
remote = true

[[vectorize]]
binding = "TARIFF_VECTORIZE"
index_name = "uk-global-tariff"
remote = true

[durable_objects]
bindings = [
  { name = "ORCHESTRATOR", class_name = "AgentOrchestrator" },
  { name = "VALIDATION_AGENT", class_name = "AgentValidationError" },
  { name = "CLASSIFIER_AGENT", class_name = "AgentClassifier" }
]

[[migrations]]
tag = "v7"
deleted_classes = ["AgentCompliance", "COMPLIANCE_AGENT", "AgentProduct", "PRODUCT_AGENT", "AgentWorkflow", "TRADE_WORKFLOW"]
new_sqlite_classes = ["AgentValidationError", "AgentClassifier"]

[ai]
binding = "AI"
remote = true
