from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from odf.opendocument import load as load_ods
from odf.table import Table, TableCell, TableRow
from odf.text import P
from openpyxl import load_workbook


ROOT = Path(__file__).resolve().parents[1]
CDS_DOC_ROOT = (
    ROOT
    / "tmp"
    / "hmrc_tdr_audit"
    / "cds_docs"
    / "CDS_Technical_Documentation_20260320"
    / "CDS 03 - Customs Declaration"
)

IMPORT_TCM = CDS_DOC_ROOT / "CDS 03 Declaration TCM for Imports v3.92.xlsx"
WCO_REFS = CDS_DOC_ROOT / "CDS 03 CDS Codelists and WCO References 5.1.0 v2.55.xlsx"
ERROR_CODES = ROOT / "tmp" / "hmrc_tdr_audit" / "CDS_Error_Codes_11-03-2026.ods"


def clean(value: Any) -> str:
    if value is None:
        return ""
    return " ".join(str(value).replace("\u00a0", " ").split())


def ts_literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2)


def write_generated_ts(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "// Generated by scripts/extract_hmrc_cds_spec.py. Do not edit by hand.\n"
        "// Source files live under tmp/hmrc_tdr_audit/cds_docs.\n\n"
        + body
        + "\n",
        encoding="utf-8",
    )


def extract_h1_data_elements() -> list[dict[str, str | int]]:
    wb = load_workbook(IMPORT_TCM, read_only=True, data_only=True)
    ws = wb["Data Completion Rules"]
    rows = list(ws.iter_rows(values_only=True))
    sub_header = rows[4]
    h1_index = next(i for i, value in enumerate(sub_header) if clean(value) == "H1")

    entries: list[dict[str, str | int]] = []
    for row_number, row in enumerate(rows[5:], start=6):
        ucc = clean(row[1] if len(row) > 1 else "")
        if not ucc:
            continue
        obligation = clean(row[h1_index] if len(row) > h1_index else "")
        if not obligation:
            continue
        entries.append(
            {
                "tcmRow": row_number,
                "ucc": ucc,
                "name": clean(row[2] if len(row) > 2 else ""),
                "wcoPath": clean(row[3] if len(row) > 3 else ""),
                "edifactColumn": clean(row[4] if len(row) > 4 else ""),
                "level": clean(row[5] if len(row) > 5 else ""),
                "cardinality": clean(row[6] if len(row) > 6 else ""),
                "format": clean(row[7] if len(row) > 7 else ""),
                "codeList": clean(row[8] if len(row) > 8 else ""),
                "description": clean(row[9] if len(row) > 9 else ""),
                "h1Obligation": obligation,
            }
        )
    return entries


def extract_wco_references() -> list[dict[str, str | int]]:
    wb = load_workbook(WCO_REFS, read_only=True, data_only=True)
    ws = wb["WCO_References_(Declaration)"]
    entries: list[dict[str, str | int]] = []
    for row_number, row in enumerate(ws.iter_rows(values_only=True), start=1):
        if row_number < 7:
            continue
        element_name = clean(row[1] if len(row) > 1 else "")
        wco_id = clean(row[2] if len(row) > 2 else "")
        wco_path = clean(row[3] if len(row) > 3 else "")
        if not element_name and not wco_id and not wco_path:
            continue
        entries.append(
            {
                "sourceRow": row_number,
                "elementName": element_name,
                "wcoId": wco_id,
                "wcoPath": wco_path,
                "format": clean(row[4] if len(row) > 4 else ""),
                "dec": clean(row[5] if len(row) > 5 else ""),
                "am": clean(row[6] if len(row) > 6 else ""),
                "remark": clean(row[7] if len(row) > 7 else ""),
            }
        )
    return entries


def node_text(node: Any) -> str:
    if hasattr(node, "data"):
        return str(node.data)
    return "".join(node_text(child) for child in getattr(node, "childNodes", []))


def ods_cell_text(cell: TableCell) -> str:
    return clean(" ".join(node_text(p) for p in cell.getElementsByType(P)))


def ods_rows(path: Path) -> list[list[str]]:
    doc = load_ods(str(path))
    table = doc.spreadsheet.getElementsByType(Table)[0]
    rows: list[list[str]] = []
    for table_row in table.getElementsByType(TableRow):
        values: list[str] = []
        for cell in table_row.getElementsByType(TableCell):
            repeat = int(cell.getAttribute("numbercolumnsrepeated") or "1")
            text = ods_cell_text(cell)
            values.extend([text] * repeat)
        while values and values[-1] == "":
            values.pop()
        if values:
            rows.append(values)
    return rows


def extract_error_codes() -> dict[str, dict[str, str]]:
    rows = ods_rows(ERROR_CODES)
    lookup: dict[str, dict[str, str]] = {}
    for row in rows[1:]:
        code = clean(row[0] if len(row) > 0 else "")
        if not code.startswith("CDS"):
            continue
        lookup[code] = {
            "description": clean(row[1] if len(row) > 1 else ""),
            "explanation": clean(row[2] if len(row) > 2 else ""),
        }
    return lookup


def main() -> None:
    h1_entries = extract_h1_data_elements()
    wco_entries = extract_wco_references()
    error_codes = extract_error_codes()

    write_generated_ts(
        ROOT / "convex" / "lib" / "cds_h1_data_elements.ts",
        "export type CdsH1DataElement = (typeof CDS_H1_DATA_ELEMENTS)[number];\n\n"
        f"export const CDS_H1_DATA_ELEMENTS = {ts_literal(h1_entries)} as const;\n",
    )
    write_generated_ts(
        ROOT / "convex" / "lib" / "cds_wco_references.ts",
        "export type CdsWcoReference = (typeof CDS_WCO_REFERENCES)[number];\n\n"
        f"export const CDS_WCO_REFERENCES = {ts_literal(wco_entries)} as const;\n",
    )
    write_generated_ts(
        ROOT / "src" / "lib" / "cds_error_codes.ts",
        "export type CdsErrorCode = keyof typeof CDS_ERROR_CODES;\n\n"
        f"export const CDS_ERROR_CODES = {ts_literal(error_codes)} as const;\n",
    )

    print(f"H1 data elements: {len(h1_entries)}")
    print(f"WCO declaration references: {len(wco_entries)}")
    print(f"CDS error codes: {len(error_codes)}")


if __name__ == "__main__":
    main()
