export interface EndUserStatementInput {
  assessmentReference: string;
  destinationCountry?: string;
  products: Array<{ name: string; techDescription?: string; quantity?: number }>;
  endUserName: string;
  endUserAddress: string;
  endUserCountry: string;
  contactName: string;
  contactEmail?: string;
  intendedUse: string;
  signedBy: string;
  signedAt: number;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatDate(ts: number): string {
  return new Date(ts).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

export function endUserStatementPrintableHtml(input: EndUserStatementInput): string {
  const goods = input.products
    .map((p) => {
      const qty = p.quantity != null ? ` (qty ${p.quantity})` : "";
      const desc = p.techDescription ? ` — ${p.techDescription}` : "";
      return `<li>${escapeHtml(p.name)}${qty}${escapeHtml(desc)}</li>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>End-User Statement — ${escapeHtml(input.assessmentReference)}</title>
  <style>
    body { font-family: system-ui, sans-serif; color: #0f172a; margin: 32px; line-height: 1.5; font-size: 13px; }
    h1 { font-size: 18px; margin: 0 0 4px; }
    .meta { color: #64748b; font-size: 12px; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    td { padding: 8px; border: 1px solid #e2e8f0; vertical-align: top; }
    td.label { width: 32%; font-weight: 600; background: #f8fafc; }
    .undertaking { margin: 16px 0; padding: 12px; border: 1px solid #e2e8f0; border-radius: 6px; }
    .footer { margin-top: 32px; font-size: 11px; color: #94a3b8; }
  </style>
</head>
<body>
  <h1>End-User Statement</h1>
  <p class="meta">Assessment ${escapeHtml(input.assessmentReference)} · Destination ${escapeHtml(input.destinationCountry ?? "—")}</p>

  <h2 style="font-size:14px;margin:24px 0 8px">Goods</h2>
  <ul>${goods || "<li>—</li>"}</ul>

  <h2 style="font-size:14px;margin:24px 0 8px">End user</h2>
  <table>
    <tr><td class="label">Organisation</td><td>${escapeHtml(input.endUserName)}</td></tr>
    <tr><td class="label">Address</td><td>${escapeHtml(input.endUserAddress || "—")}</td></tr>
    <tr><td class="label">Country</td><td>${escapeHtml(input.endUserCountry || "—")}</td></tr>
    <tr><td class="label">Contact</td><td>${escapeHtml(input.contactName)}${input.contactEmail ? ` (${escapeHtml(input.contactEmail)})` : ""}</td></tr>
    <tr><td class="label">Intended end use</td><td>${escapeHtml(input.intendedUse)}</td></tr>
  </table>

  <div class="undertaking">
    <p>The end user confirms that the goods will not be used for any prohibited end use, including development or production of weapons of mass destruction or their means of delivery.</p>
    <p>The end user confirms that the goods will not be re-exported or diverted to a prohibited destination or end user without the exporter's prior written consent and any required licence.</p>
  </div>

  <table>
    <tr><td class="label">Signed by</td><td>${escapeHtml(input.signedBy)}</td></tr>
    <tr><td class="label">Date</td><td>${formatDate(input.signedAt)}</td></tr>
  </table>

  <p class="footer">Generated by Freightcode for LITE/SPIRE supporting documentation. Not a licence or legal advice.</p>
</body>
</html>`;
}

function printViaIframe(html: string): boolean {
  const iframe = document.createElement("iframe");
  iframe.style.position = "fixed";
  iframe.style.right = "0";
  iframe.style.bottom = "0";
  iframe.style.width = "0";
  iframe.style.height = "0";
  iframe.style.border = "none";
  document.body.appendChild(iframe);
  const doc = iframe.contentDocument ?? iframe.contentWindow?.document;
  if (!doc) return false;
  doc.open();
  doc.write(html);
  doc.close();
  iframe.contentWindow?.focus();
  iframe.contentWindow?.print();
  window.setTimeout(() => {
    if (iframe.parentNode) document.body.removeChild(iframe);
  }, 1000);
  return true;
}

export function openEndUserStatementPrintDialog(input: EndUserStatementInput): boolean {
  const html = endUserStatementPrintableHtml(input);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, "_blank");

  if (!win) {
    URL.revokeObjectURL(url);
    return printViaIframe(html);
  }

  const triggerPrint = () => {
    win.focus();
    win.print();
    window.setTimeout(() => URL.revokeObjectURL(url), 60_000);
  };

  if (win.document.readyState === "complete") {
    triggerPrint();
  } else {
    win.addEventListener("load", triggerPrint, { once: true });
  }

  return true;
}
